# Generated by Django 5.1.6 on 2025-02-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/desy8wuw7/image/upload/v1740053714/default_profile_gg8l4z.png', null=True, upload_to='', verbose_name='users/'),
        ),
    ]
