# Generated by Django 5.1.6 on 2025-02-21 02:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/desy8wuw7/image/upload/v1740053714/default_profile_gg8l4z.png', max_length=255, null=True, verbose_name='users/'),
        ),
    ]
