# Generated by Django 5.1.6 on 2025-02-20 12:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/desy8wuw7/image/upload/v1740053714/default_item_mnkqtc.png', max_length=255, null=True, verbose_name='categories/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/desy8wuw7/image/upload/v1740053714/default_item_mnkqtc.png', max_length=255, null=True, verbose_name='products/'),
        ),
    ]
